name             'mo_reverse_proxy'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mo_reverse_proxy'
long_description 'Installs/Configures mo_reverse_proxy'
version          '1.0.0'

depends   'certificate',      '~>0.6.3'
depends   'mo_application',   '~>1.0.0'
